{{- if .Values.postgres.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.postgres.auth.secretName }}
  labels:
    {{- include "hello-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  encryptedData:
    POSTGRES_DB: {{ .Values.postgres.auth.encryptedDatabase | quote }}
    POSTGRES_USER: {{ .Values.postgres.auth.encryptedUsername | quote }}
    POSTGRES_PASSWORD: {{ .Values.postgres.auth.encryptedPassword | quote }}
  template:
    metadata:
      name: {{ .Values.postgres.auth.secretName }}
      labels:
        {{- include "hello-api.labels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    type: Opaque
{{- end }}
