{{- if .Values.registryCredentials.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.registryCredentials.name }}
  labels:
    {{- include "hello-api.labels" . | nindent 4 }}
spec:
  encryptedData:
    .dockerconfigjson: {{ .Values.registryCredentials.encryptedDockerConfigJson | quote }}
  template:
    metadata:
      name: {{ .Values.registryCredentials.name }}
      labels:
        {{- include "hello-api.labels" . | nindent 8 }}
    type: kubernetes.io/dockerconfigjson
{{- end }}
