{{- if .Values.secrets.runtime.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secrets.runtime.name }}
  labels:
    {{- include "hello-api.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    {{ .Values.secrets.runtime.key }}: {{ required "secrets.runtime.encryptedValue is required" .Values.secrets.runtime.encryptedValue | quote }}
  template:
    metadata:
      name: {{ .Values.secrets.runtime.name }}
      labels:
        {{- include "hello-api.labels" . | nindent 8 }}
    type: Opaque
{{- end }}
